# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5515bf613878284e2015e3acdcde0d8d78f2c5e6b3f656ad04dff8a1071957dcc512752d0cfc7ba15573eac8e442c38326312dab11cf5d46e722c0ba36bc0838

test:
  secret_key_base: 9d13b3eabf24fc82e51d1cc07314755fb6c9b68f74260c15c53e08caa773abef4873572f56d33a14db2e776d7bdd01888f9117bd51d46f31903e3988f8ae862a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
